### ISSUE TITLE
Asking for a new release on PyPi

### ISSUE THREAD

**Issue by matteofumagalli1275** [letuananh/chirptext#3]
Hi,

Version 0.1a18 is a bit outdated, could you update a newer version to PyPi?

I only need this [commit](https://github.com/letuananh/chirptext/commit/0f7b8d8843baa83fa08df2e8f0432a531b73980b), but since long time is passed i think most of the master change are stable.

**Comment by letuananh** [comment]
Hi thank you for contacting. I have just release version 0.1a19 about an hour ago on PyPI.
